Table follows {
  following_user_id integer [ref: > users.id]
  followed_user_id integer [ref: > users.id]
  created_at timestamp
}

Table users {
  id integer [pk]
  username varchar
  role varchar
  profile varchar
  created_at timestamp
}

Table posts {
  id integer [primary key]
  title varchar
  body text [note: 'Content of the post']
  comment varchar
  user_id integer [ref: > users.id , not null]
  status varchar
  created_at timestamp
}
